Added post-cards-logic
Charlysa45/Instagram-Rednajava pull request #7
Opened 2022-06-23 22:36 UTC by PhoenixDwarf

Added general logic, imported api array, displayed all cards, optimized styling, updated api json file

2022-06-23 22:42 UTC, Charlysa45 approved these changes

2022-06-23 22:44 UTC, Wilmerj requested changes

2022-06-23 22:44 UTC, Wilmerj commented on src/pages/Home/components/post-card/post-card.js
> +    apiJson.map((res)=>{
Podemos destructurar el objeto para que el codigo quede mejor, busquemos que es `destructuring en js`

2022-06-23 22:44 UTC, Wilmerj commented on src/pages/Home/components/post-card/post-card.js
>                              <button><img src={likes} alt="likes"></img></button>
Al ser una etiqueta que no contiene nada podemos cerrarla en ella misma, Ej: `<img src={comments} alt="comments" />`

2022-06-24 00:56 UTC, PhoenixDwarf commented on src/pages/Home/components/post-card/post-card.js
>                              <button><img src={likes} alt="likes"></img></button>
Done

2022-06-24 01:41 UTC, merged