feature/responsive-design
Charlysa45/Instagram-Rednajava pull request #9
Opened 2022-07-07 20:34 UTC by PhoenixDwarf

Added general responsive behavior to the whole app.

2022-07-07 21:29 UTC, Charlysa45 approved these changes

2022-07-08 15:52 UTC, Wilmerj requested changes

2022-07-08 15:52 UTC, Wilmerj commented on src/pages/Home/components/Header/Header.css
> +    z-index: 1000;
Tratemos de no usar z-index, si es 100% obligatorio si, pero caso contrario que podamos posicionar los elementos de manera que no tengamos que usarlo mucho mejor

2022-07-08 15:52 UTC, Wilmerj commented on src/pages/Home/components/Header/Header.js
> +    <div id='main-container'>
La etiqueta padre deberia ser el header ya que es lo primero que raspa el crawler

2022-07-08 21:08 UTC, merged